[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99775b50ab20150e37892addea8e0c8d4b129e34"
libc = "glibc"
llvm = "12"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "bddd05ceb5253892525eaaa26c365420ab9d65444bce522cfb5abbc33b68e026"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+12.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0167590b92c317246186182cdc13fbdb9738589f"
libc = "glibc"
llvm = "13"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "c8c86b41352c1a9dc758a2d8f23d105f65ae2831aead572c211fadb5ded41c99"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0dce16205dbf1ace05bd78f278928eaa6fe8284"
libc = "glibc"
llvm = "13.asserts"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "8fb8c5800ebffe87835fdef9f6d6648baa35ab998cef0826fa53efa7c7b1ca22"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.asserts.tar.gz"
