[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa09e03ade8afb9df1bc80d934995f78565c1199"
libc = "glibc"
llvm = "12"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "5b05c7e297476dfec5825c6862efe101ccb02642abd9854cecec6641d0c0addc"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+12.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50ad33f91c7a8da67075c5fbe76f57ae2725f8ad"
libc = "glibc"
llvm = "13"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "294b9470a9141d3da8ddece455fbe71ea0789bb616b091f3aad5fb0af2dfc75a"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32b9a1d3dfb8d19a2f660f48c7a22dcc53a7ccb2"
libc = "glibc"
llvm = "13.asserts"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "52a697dc7972d656e471ddf4181a183e6296f141033d2ee4df87d203dccf2d0d"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.asserts.tar.gz"
