[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d43894fdce9bccaed7cdb828b72253b55dd6e8c4"
libc = "glibc"
llvm = "12"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "a75c7ceca7896b424bf8c7f96d4a3507b3e376cc6bfc478160764110aafd9b57"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+12.tar.gz"
