[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c950d407b40b3730a3b4ec804317400bdc44c2a6"
libc = "glibc"
llvm = "13"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "eaf9954ee462c05535e3a91fa9f894e875120524a546754e1451b4c38e35d199"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ffdf974249c235685f8e9958326ec0fc8ac44e8"
libc = "glibc"
llvm = "12"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "f687d562362fa24e1dcf336ec956b341371fb5489ce79f98f953e0b17de6abd9"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+12.tar.gz"
