[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09564b2f57521466e5b6943452d0e687f69f8cab"
libc = "glibc"
llvm = "12"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "6e32957d3aa2bc48c03050450ab2ef7d1243f911c543a2da22e59d8a7e82b63b"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+12.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "947b404beeeb8772c4b9070eb4af8e1ad0f89648"
libc = "glibc"
llvm = "13"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "73d102a68f2e5b15d78dfe8c221709a6c96f9c1707db4d1eb6a8860d82734028"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.tar.gz"
[[SPIRV_LLVM_Translator_unified]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "308cf7725fbca0a79a13afd16c2e45305e867b4d"
libc = "glibc"
llvm = "13.asserts"
os = "linux"

    [[SPIRV_LLVM_Translator_unified.download]]
    sha256 = "44619a7ec05b95fb54c30a246b822c081c8c6272825391c2d293cfa3c947da92"
    url = "https://github.com/maleadt/SPIRV_LLVM_Translator_unified_jll.jl/releases/download/SPIRV_LLVM_Translator_unified-v0.1.0+0/SPIRV_LLVM_Translator_unified.v0.1.0.x86_64-linux-gnu-cxx11-llvm+13.asserts.tar.gz"
